"""Adicionando relacionamento de um ou mais times campeoes e vices de uma edicao

Revision ID: 0023c1aa7b57
Revises: d626c777b08f
Create Date: 2026-07-31 23:03:31.102513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0023c1aa7b57'
down_revision: Union[str, None] = 'd626c777b08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edition_champions',
    sa.Column('edition_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edition_id', 'team_id')
    )
    op.create_table('edition_runners_up',
    sa.Column('edition_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edition_id', 'team_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edition_runners_up')
    op.drop_table('edition_champions')
    # ### end Alembic commands ###