"""corrigindo array das cores com JSON

Revision ID: 0ecf71ba972a
Revises: 3f01f70c9c3a
Create Date: 2026-03-20 20:13:56.339153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ecf71ba972a'
down_revision: Union[str, None] = '3f01f70c9c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'colors',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using='colors::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'colors',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###