"""corrigindo array das cores

Revision ID: 3f01f70c9c3a
Revises: d54054c26ffe
Create Date: 2026-03-20 20:08:48.659347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f01f70c9c3a'
down_revision: Union[str, None] = 'd54054c26ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###