"""Adicionando enum na tipagem

Revision ID: b36395c9a50d
Revises: 2a0360844ada
Create Date: 2026-03-22 01:14:48.858329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36395c9a50d'
down_revision: Union[str, None] = '2a0360844ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    entity_type_enum = sa.Enum('TEAM', 'STADIUM', 'COMPETITION', name='entitytypesenum')
    entity_type_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('photos', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               type_=entity_type_enum,
               existing_nullable=False,
               postgresql_using='entity_type::entitytypesenum')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'entity_type',
               existing_type=sa.Enum('TEAM', 'STADIUM', 'COMPETITION', name='entitytypesenum'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###

    sa.Enum(name='entitytypesenum').drop(op.get_bind(), checkfirst=True)