"""Adicionando mais atributos em times e estadio

Revision ID: d54054c26ffe
Revises: c62ec76ae715
Create Date: 2026-03-20 00:19:55.710368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd54054c26ffe'
down_revision: Union[str, None] = 'c62ec76ae715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stadiums', sa.Column('nickname', sa.String(length=100), nullable=False))
    op.add_column('stadiums', sa.Column('address', sa.String(length=100), nullable=False))
    op.add_column('teams', sa.Column('sigla', sa.String(length=100), nullable=False))
    op.add_column('teams', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('teams', sa.Column('state', sa.Enum('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO', name='stateenum'), nullable=False))
    op.add_column('teams', sa.Column('colors', sa.String(length=100), nullable=False))
    op.add_column('teams', sa.Column('alcunha_color', sa.String(length=100), nullable=False))
    op.add_column('teams', sa.Column('mascot', sa.String(length=100), nullable=False))
    op.add_column('teams', sa.Column('subscribers_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'subscribers_count')
    op.drop_column('teams', 'mascot')
    op.drop_column('teams', 'alcunha_color')
    op.drop_column('teams', 'colors')
    op.drop_column('teams', 'state')
    op.drop_column('teams', 'city')
    op.drop_column('teams', 'sigla')
    op.drop_column('stadiums', 'address')
    op.drop_column('stadiums', 'nickname')
    # ### end Alembic commands ###