"""adicionando placares de uma disputa de penalties em matches

Revision ID: d626c777b08f
Revises: 66f6b3a98b9c
Create Date: 2026-07-30 12:59:51.304102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd626c777b08f'
down_revision: Union[str, None] = '66f6b3a98b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('home_penalty_score', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('away_penalty_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'away_penalty_score')
    op.drop_column('matches', 'home_penalty_score')
    # ### end Alembic commands ###